name: Test

on: [push, pull_request]

jobs:
  test_without_simd:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Build tests
      run: |
        cmake -S test -B build -Wno-dev
        cmake --build build --config Debug

    - name: Run tests
      run: |
        cd build
        ctest -C Debug --output-on-failure
