name: Test

on: [push, pull_request]

jobs:
  test_without_simd:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Detect features
      run: |
        cmake -S detect -B detect-build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=23 -Wno-dev
        cmake --build detect-build --config Debug

    - name: Build tests
      run: |
        cmake -S test -B build -DCMAKE_BUILD_TYPE=Debug -Wno-dev
        cmake --build build --config Debug

    - name: Run tests
      working-directory: build
      run: |
        ctest -C Debug --output-on-failure
